name: Release Application Code and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  release-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create zip of the application code
      run: |
        zip -r app_code_${{ github.sha }}.zip .

    - name: Extract short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} .

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

    - name: Create GitHub release and upload the zip file
      uses: softprops/action-gh-release@v1
      with:
        files: app_code_${{ github.sha }}.zip 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
